services:
    myapp_user.activity_listener:
        class: MyApp\UserBundle\Listener\ActivityListener
        arguments: ['@security.token_storage', '@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }
    my_app_user.form.flow.createVehicle:
            class: MyApp\UserBundle\Form\AnnonceFlow
            parent: craue.form.flow